[2024-03-31T08:44:18.443+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_parquet_gcs.upload_parquet_to_gcs manual__2024-03-31T08:43:51.078137+00:00 [queued]>
[2024-03-31T08:44:18.454+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_parquet_gcs.upload_parquet_to_gcs manual__2024-03-31T08:43:51.078137+00:00 [queued]>
[2024-03-31T08:44:18.454+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-31T08:44:18.470+0000] {taskinstance.py:2217} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_parquet_to_gcs> on 2024-03-31 08:43:51.078137+00:00
[2024-03-31T08:44:18.479+0000] {standard_task_runner.py:60} INFO - Started process 1334 to run task
[2024-03-31T08:44:18.486+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'data_parquet_gcs', 'upload_parquet_to_gcs', 'manual__2024-03-31T08:43:51.078137+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/dataset_prepare_gcs.py', '--cfg-path', '/tmp/tmpvyh88y41']
[2024-03-31T08:44:18.490+0000] {standard_task_runner.py:88} INFO - Job 74: Subtask upload_parquet_to_gcs
[2024-03-31T08:44:18.557+0000] {task_command.py:423} INFO - Running <TaskInstance: data_parquet_gcs.upload_parquet_to_gcs manual__2024-03-31T08:43:51.078137+00:00 [running]> on host 494f44035b7c
[2024-03-31T08:44:18.662+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_parquet_gcs' AIRFLOW_CTX_TASK_ID='upload_parquet_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-03-31T08:43:51.078137+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-31T08:43:51.078137+00:00'
[2024-03-31T08:44:18.688+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-03-31T08:44:18.691+0000] {base.py:83} INFO - Using connection ID 'gcp' for task execution.
[2024-03-31T08:44:18.964+0000] {gcs.py:510} ERROR - Upload attempt of object: final_project/parquet/job_postings/part-00003-8c90dde5-64d2-455e-9fe6-6645740c8a42-c000.snappy.parquet from final_project/parquet/job_postings/part-00003-8c90dde5-64d2-455e-9fe6-6645740c8a42-c000.snappy.parquet has failed. Attempt: 1, max 1.
[2024-03-31T08:44:18.965+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 2637, in _prep_and_do_upload
    created_json = self._do_upload(
                   ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 2443, in _do_upload
    response = self._do_multipart_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 1956, in _do_multipart_upload
    response = upload.transmit(
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/google/resumable_media/requests/upload.py", line 153, in transmit
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/google/resumable_media/requests/upload.py", line 149, in retriable_request
    self._process_response(result)
  File "/usr/local/lib/python3.11/site-packages/google/resumable_media/_upload.py", line 125, in _process_response
    _helpers.require_status_code(response, (http.client.OK,), self._get_status_code)
  File "/usr/local/lib/python3.11/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 110, in execute
    hook.upload(
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 549, in upload
    _call_with_retry(
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 517, in _call_with_retry
    raise e
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 507, in _call_with_retry
    f()
  File "/usr/local/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 2959, in upload_from_filename
    self._handle_filename_and_upload(
  File "/usr/local/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 2829, in _handle_filename_and_upload
    self._prep_and_do_upload(
  File "/usr/local/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 2655, in _prep_and_do_upload
    _raise_from_invalid_response(exc)
  File "/usr/local/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 4847, in _raise_from_invalid_response
    raise exceptions.from_http_status(response.status_code, message, response=response)
google.api_core.exceptions.Forbidden: 403 POST https://storage.googleapis.com/upload/storage/v1/b/de-zoomcamp-xiangivyli/o?uploadType=multipart: {
  "error": {
    "code": 403,
    "message": "airflow-gcs-bigquery@cedar-style-412618.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist).",
    "errors": [
      {
        "message": "airflow-gcs-bigquery@cedar-style-412618.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist).",
        "domain": "global",
        "reason": "forbidden"
      }
    ]
  }
}
: ('Request failed with status code', 403, 'Expected one of', <HTTPStatus.OK: 200>)
[2024-03-31T08:44:18.990+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=data_parquet_gcs, task_id=upload_parquet_to_gcs, execution_date=20240331T084351, start_date=20240331T084418, end_date=20240331T084418
[2024-03-31T08:44:19.008+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 74 for task upload_parquet_to_gcs (403 POST https://storage.googleapis.com/upload/storage/v1/b/de-zoomcamp-xiangivyli/o?uploadType=multipart: {
  "error": {
    "code": 403,
    "message": "airflow-gcs-bigquery@cedar-style-412618.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist).",
    "errors": [
      {
        "message": "airflow-gcs-bigquery@cedar-style-412618.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist).",
        "domain": "global",
        "reason": "forbidden"
      }
    ]
  }
}
: ('Request failed with status code', 403, 'Expected one of', <HTTPStatus.OK: 200>); 1334)
[2024-03-31T08:44:19.060+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-31T08:44:19.086+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
